version: '3.8'

services:
  app:
    build: .
    container_name: diploma_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app  # чтобы база сохранялась
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data: